set(K_HAL_SRCS ${CMAKE_CURRENT_LIST_DIR}/src/${K_HAL_PLATFORM}/k_hal_i2c_master.c)
set(K_HAL_PUBLIC_INCLUDES ${CMAKE_CURRENT_LIST_DIR}/include)
set(K_HAL_PRIVATE_INCLUDES ${CMAKE_CURRENT_LIST_DIR}/src/${K_HAL_PLATFORM})
set(K_HAL_PUBLIC_LINKS)
set(K_HAL_PRIVATE_LINKS)

function(create_mock_library)
    add_library(k_hal_mock ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/mock/k_hal_i2c_master_mock.c)
    target_include_directories(k_hal_mock PUBLIC ${CMAKE_CURRENT_FUNCTION_LIST_DIR}/include)
    target_link_libraries(k_hal_mock PUBLIC fff)
endfunction()